### ISSUE TITLE
Polyglot Monorepo Support: Extend khive fmt for all languages

### ISSUE THREAD

**Issue by ohdearquant** [khive-ai/khive.d#135]
## Overview
Extend `khive fmt` to support formatting for all languages in our polyglot monorepo, ensuring consistent code style across the entire codebase with a single command.

## Current State
- Python support via Ruff
- Rust support via cargo fmt
- Markdown/TypeScript support via Deno fmt
- Basic parallel execution

### 1. Additional Language Support
- **Go**: Integration with `gofmt` or `goimports`
- **JavaScript/TypeScript**: Enhanced support with Prettier/ESLint
- **YAML/JSON**: Schema-aware formatting
- **Shell scripts**: ShellCheck + shfmt integration
- **Dockerfile**: hadolint integration
- **TOML**: taplo integration

### 2. Smart Language Detection
- Auto-detect languages based on file extensions and content
- Support for mixed-language files (e.g., Markdown with code blocks)
- Language-specific configuration in `.khive/fmt.toml`

### 3. Performance Optimizations
- Implement file-level caching based on content hashes
- Skip unchanged files since last successful format
- Parallel execution with proper resource management

### 4. Integration Features
- Hook into `khive ci` for pre-commit formatting
- Support for `--check` mode across all formatters
- Unified error reporting and exit codes

## Configuration Example
```toml
[tool.khive.fmt]
enable = ["python", "rust", "go", "typescript", "yaml", "shell", "dockerfile"]

[tool.khive.fmt.stacks.go]
cmd = "goimports -w {files}"
check_cmd = "goimports -d {files}"
include = ["*.go"]
exclude = ["vendor/**", "*_generated.go"]

[tool.khive.fmt.stacks.yaml]
cmd = "yamlfmt {files}"
check_cmd = "yamlfmt -d {files}"
include = ["*.yaml", "*.yml"]
schema_validation = true
```

## Acceptance Criteria
- [ ] All major languages in the monorepo are supported
- [ ] Single `khive fmt` command formats entire codebase
- [ ] Performance: <5s for full monorepo format check
- [ ] Language-specific configurations are respected
- [ ] Proper integration with `khive ci`
- [ ] Clear documentation for adding new languages

## Dependencies
- #127 (Enhance khive fmt with iterative auto-fixing)
- Research from deep research documents

## References
- Designing robust local CI checks document
- Building Intelligent, Context-Aware CLI Systems document
