### ISSUE TITLE
Polyglot CI: One command to test them all

### ISSUE THREAD

**Issue by ohdearquant** [khive-ai/khive.d#136]
## Overview
Enhance the `khive ci` command to run all tests and checks for the entire polyglot monorepo with a single command, providing unified CI/CD capabilities across all languages and frameworks.

### 1. Language-Specific Test Discovery
- **Python**: pytest, unittest, doctest
- **Rust**: cargo test, cargo bench
- **Go**: go test, go bench
- **TypeScript/JavaScript**: jest, vitest, mocha
- **Shell**: bats, shellcheck

### 2. Unified Test Execution
```bash
# Run all tests across all languages
khive ci

# Run tests for specific stacks
khive ci --stack python,rust

# Run only fast tests
khive ci --fast

# Run with coverage
khive ci --coverage
```

### 3. Dependency-Aware Testing
- Detect which files changed
- Run only tests affected by changes
- Build dependency graph for smart test selection
- Cache test results based on file hashes

### 4. Parallel Execution Strategy
- Language-level parallelism (run Python and Rust tests simultaneously)
- Test-level parallelism within each language
- Resource-aware scheduling to prevent overload

### 5. Unified Reporting
```json
{
  "status": "passed",
  "duration": 45.2,
  "languages": {
    "python": {
      "status": "passed",
      "tests_run": 342,
      "tests_passed": 342,
      "coverage": 89.5
    },
    "rust": {
      "status": "passed",
      "tests_run": 128,
      "tests_passed": 128,
      "coverage": 92.1
    }
  },
  "stamp": "ci-2024-11-21-abc123"
}
```

### 6. Integration Points
- Pre-commit hook integration
- GitHub Actions compatibility
- Approval stamp generation for `khive commit` and `khive pr`
- Cache sharing between local and CI environments

## Configuration
```toml
[tool.khive.ci]
parallel = true
max_workers = 4
cache_dir = ".khive/ci-cache"

[tool.khive.ci.python]
test_command = "pytest -v"
coverage_command = "pytest --cov=src"
fast_markers = ["not slow", "not integration"]

[tool.khive.ci.rust]
test_command = "cargo test"
coverage_command = "cargo tarpaulin"
exclude_packages = ["benchmarks"]

[tool.khive.ci.validation]
required_coverage = 80
max_warnings = 10
enforce_typing = true
```

## Acceptance Criteria
- [ ] Single command runs all tests across all languages
- [ ] Parallel execution with proper resource management
- [ ] Smart test selection based on changed files
- [ ] Unified JSON/human-readable output
- [ ] CI stamp generation and validation
- [ ] <30s for incremental test runs
- [ ] Integration with existing CI providers

## Dependencies
- #126 (Implement khive ci command)
- #135 (Polyglot fmt support)

## References
- Research documents on local CI checks
- Building Intelligent, Context-Aware CLI Systems
