### ISSUE TITLE
Advanced Git Integration: Parallel hooks, conflict resolution, and branch-aware validation

### ISSUE THREAD

**Issue by ohdearquant** [khive-ai/khive.d#139]
## Overview
Implement advanced Git workflow integration patterns based on the research, providing sophisticated automation while maintaining developer control.

### 1. Parallel Hook Execution System
```yaml
# .khive/hooks.yaml
pre-commit:
  parallel: true
  max_workers: 4
  hooks:
    - name: format-python
      glob: "*.py"
      command: "ruff format {staged_files}"
      stage_fixed: true
    - name: format-rust
      glob: "*.rs"
      command: "cargo fmt -- {staged_files}"
    - name: lint-typescript
      glob: "*.{ts,tsx}"
      command: "eslint --fix {staged_files}"
```

### 2. Branch-Aware Validation
```bash
# Different validation based on branch
khive ci --branch main      # Full validation suite
khive ci --branch feature/* # Fast checks only
khive ci --branch release/* # Security + compliance checks

# Auto-detect current branch context
khive ci  # Applies appropriate rules
```

### 3. Pre-flight Conflict Detection
```bash
# Check for conflicts before creating PR
khive pr --check-conflicts

# Output:
✓ No conflicts with main branch
✓ All CI checks would pass
✓ Ready to create PR

# Or with conflicts:
✗ Conflicts detected in 3 files:
  - src/main.rs (line 45-67)
  - Cargo.toml (dependencies)
  - README.md (documentation)
  
Run 'khive resolve' for guided resolution
```

### 4. Intelligent Conflict Resolution
```bash
# Interactive conflict resolution
khive resolve

# Auto-resolve safe conflicts
khive resolve --auto
  ✓ Resolved formatting conflicts in 5 files
  ✓ Resolved import order in 3 files
  ? Manual resolution needed for src/api.rs
```

### 5. Hybrid Metadata Storage
- **Commit Trailers**: For shareable metadata (CI status, approvals)
- **Local Cache**: For performance data and temporary state
- **Query Interface**: Unified access to both storage types

```bash
# Add metadata to commits
khive commit --with-trailer "CI-Status: passed"

# Query metadata
khive log --show-ci-status
```

### 6. Hook Multiplexing
```bash
# Install khive hooks alongside existing tools
khive hooks install --compatible

# What it does:
# 1. Detects existing hook managers (Husky, Lefthook)
# 2. Installs multiplexer that coordinates all hooks
# 3. Preserves existing functionality
# 4. Adds khive enhancements
```

### Hook Manager
```python
class HookManager:
    def install_hooks(self, compatible_mode: bool = True):
        """Install Git hooks with multiplexing support"""
        
    def run_parallel(self, hooks: List[Hook], files: List[Path]):
        """Execute hooks in parallel with proper isolation"""
        
    def detect_conflicts(self, hook_results: List[Result]):
        """Detect when hooks conflict with each other"""
```

### Branch Context Detector
```python
class BranchContext:
    def get_validation_rules(self) -> ValidationRules:
        """Get appropriate rules for current branch"""
        
    def is_protected_branch(self) -> bool:
        """Check if current branch has special rules"""
```

### Conflict Analyzer
```python
class ConflictAnalyzer:
    def check_merge_conflicts(self, target_branch: str) -> List[Conflict]:
        """Pre-flight conflict detection using git merge-tree"""
        
    def categorize_conflicts(self, conflicts: List[Conflict]):
        """Separate auto-resolvable from manual conflicts"""
        
    def auto_resolve(self, conflict: Conflict) -> bool:
        """Attempt automatic resolution for safe conflicts"""
```

## Configuration
```toml
[tool.khive.git]
parallel_hooks = true
hook_timeout = 30  # seconds
conflict_detection = "pre-flight"

[tool.khive.git.branch_rules]
"main" = { validation = "comprehensive", security_scan = true }
"feature/*" = { validation = "fast", auto_format = true }
"release/*" = { validation = "security", require_approval = true }

[tool.khive.git.metadata]
storage = "hybrid"  # trailers + local cache
trailer_prefix = "X-Khive-"
cache_ttl = 86400  # 24 hours
```

## Acceptance Criteria
- [ ] Hooks run in parallel with 60-80% time reduction
- [ ] Branch-aware validation reduces CI time by 50%
- [ ] Conflict detection prevents 95% of merge conflicts
- [ ] Auto-resolution handles 80% of formatting conflicts
- [ ] Metadata access <5ms for local cache
- [ ] Compatible with existing Git tools

## Dependencies
- Research: Advanced Git Workflow Integration document
- #126 (khive ci implementation)
- #127 (khive fmt enhancements)

## References
- Lefthook parallel execution patterns
- Git merge-tree documentation
- Hybrid metadata approach analysis
