### ISSUE TITLE
Comprehensive Testing Infrastructure for khive CLI

### ISSUE THREAD

**Issue by ohdearquant** [khive-ai/khive.d#140]
## Overview
Establish comprehensive testing infrastructure for all khive CLI commands, ensuring reliability, performance, and cross-platform compatibility.

### 1. Unit Test Framework
- **Coverage Target**: Minimum 80% for all CLI modules
- **Testing Libraries**: 
  - Python: pytest with async support
  - Rust: built-in test framework
  - TypeScript: vitest for speed
- **Mock Infrastructure**: Consistent mocking for external dependencies

### 2. Integration Test Suite
```python
# Example integration test structure
class TestKhiveCIIntegration:
    async def test_full_ci_workflow(self, project_fixture):
        """Test complete CI workflow from staging to approval"""
        # 1. Make changes
        # 2. Run khive fmt
        # 3. Run khive ci
        # 4. Verify stamp creation
        # 5. Run khive commit
        # 6. Verify stamp validation
        
    async def test_polyglot_execution(self, polyglot_project):
        """Test CI across multiple languages"""
        result = await run_cli(["khive", "ci"])
        assert result.languages_tested == ["python", "rust", "go"]
```

### 3. End-to-End Test Scenarios
- **New Developer Onboarding**: Full workflow from clone to first PR
- **Release Workflow**: Version bump, changelog, tag, publish
- **Emergency Hotfix**: Fast-track validation and deployment
- **Team Collaboration**: Multi-user cache and state sync

### 4. Performance Benchmarks
```yaml
# .khive/benchmarks.yaml
benchmarks:
  - name: full-ci-execution
    target: < 30s
    measure: ["wall-time", "cpu-time", "memory-peak"]
    
  - name: incremental-ci
    target: < 5s
    conditions: ["single-file-change"]
    
  - name: format-monorepo
    target: < 10s
    measure: ["parallel-efficiency"]
```

### 5. Cross-Platform Testing Matrix
```yaml
# CI configuration
test-matrix:
  os: [ubuntu-latest, macos-latest, windows-latest]
  python: ["3.9", "3.10", "3.11", "3.12"]
  rust: ["stable", "beta"]
  node: ["18", "20"]
```

### 6. Security Testing
- **Dependency Scanning**: Check for known vulnerabilities
- **Secret Detection**: Ensure no credentials in code/logs
- **Input Fuzzing**: Test command parsing robustness
- **Privilege Escalation**: Verify no unintended permissions

### 7. CLI Behavior Testing
```bash
# Test all commands support common flags
for cmd in init commit pr clean fmt ci info reader; do
  khive $cmd --help
  khive $cmd --json-output --dry-run
  khive $cmd --verbose
done

# Test error handling
khive ci --invalid-flag  # Should show helpful error
khive fmt /nonexistent   # Should handle gracefully
```

### Directory Structure
```
tests/
├── unit/
│   ├── cli/
│   │   ├── test_khive_ci.py
│   │   ├── test_khive_fmt.py
│   │   └── test_khive_commit.py
│   └── services/
│       ├── test_cache_service.py
│       └── test_notification_service.py
├── integration/
│   ├── test_full_workflows.py
│   ├── test_polyglot_support.py
│   └── test_team_collaboration.py
├── e2e/
│   ├── scenarios/
│   └── fixtures/
├── benchmarks/
│   └── test_performance.py
└── security/
    └── test_security_controls.py
```

### Test Utilities
```python
# tests/utils.py
class CLITestHelper:
    async def run_command(self, args: List[str]) -> CLIResult:
        """Run khive command and capture output"""
        
    def create_test_repo(self, template: str) -> Path:
        """Create test repository from template"""
        
    async def assert_ci_passed(self, project: Path):
        """Assert CI validation passed"""
```

### Pre-commit Checks
- All tests pass
- Code coverage maintained
- No security vulnerabilities
- Documentation updated

### CI Pipeline
- Full test matrix execution
- Performance benchmarks pass
- Security scan clean
- Cross-platform validation

## Acceptance Criteria
- [ ] 80%+ code coverage across all modules
- [ ] All integration tests pass on all platforms
- [ ] Performance benchmarks meet targets
- [ ] Security tests identify no vulnerabilities
- [ ] Test execution time < 5 minutes locally
- [ ] Clear test documentation and examples

## Dependencies
- All CLI implementation issues (#126-#139)
- Testing framework setup
- CI/CD pipeline configuration

## Priority
HIGH - Testing is essential for reliability and maintainability
